apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    name: db-deployment
    app: my-voting-app
    
    
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db-pod
      app: my-voting-app
  template:
    metadata:
      name: db-pod
      labels:
        name: db-pod
        app: my-voting-app
    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
        ports:
          - containerPort: 5432
