apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis-deployment
    app: my-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-voting-app
      name: redis-pod
  template:
    metadata:
      name: redis-pod
      labels:
        app: my-voting-app
        name: redis-pod
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
