apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    name: result-deployment
    app: my-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-voting-app
      name: result-pod
  template:
    metadata:
      name: result-pod
      labels:
        app: my-voting-app
        name: result-pod
    spec:
      containers:
      - name: result-app
        image: kodekloud/examplevotingapp_result:v1
        ports:
        - containerPort: 80
