apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: my-voting-app
spec:
  type: NodePort
  selector:
    name: result-pod
    app: my-voting-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005